name = "svustatus"
pages_build_output_dir = "dist"
compatibility_date = "2026-05-10"
compatibility_flags = ["nodejs_compat"]

[vars]
SITE_URL = "https://svustatus.pages.dev"
PUBLIC_STATUS_DATA_URL = "https://raw.githubusercontent.com/shadi-almilhem/svustatus/status-data/status.json"
VAPID_PUBLIC_KEY = "BFQtVUqxU1HC-qEML8zeyXZrEFqR6is0ZFJaAanRxoqevnE5mEwIoHN0C1tUpXf4C7fmc-GrFQmLgQWjxGuDNfs"

[[services]]
binding = "OG_RENDERER"
service = "svustatus-og-renderer"

[[kv_namespaces]]
binding = "STATUS_KV"
id = "3c04fc2d620f4cdd82ec851375c84aba"

[[d1_databases]]
binding = "WATCH_DB"
database_name = "svustatus-watch"
database_id = "5c8b741d-eb30-42ab-adc6-7e1006368d6b"
